[PTT-178] configure service min max tefa
pagopa/hub-pa-fe pull request #21
Opened 2021-05-24 08:32 UTC by filma80

#### List of Changes
Fixed min and max value for secondary percentage (TEFA) to 0.01/99.99.
Updated form validator and input min/max values.

#### Motivation and Context
Value of 0 is not allowed.

#### How Has This Been Tested?
Unit and integration tests.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-05-24 09:48 UTC, GiovanniMancini commented on src/app/pages/tributi-page/tributi-step1-imposta-enti/tributi-step1-imposta-enti.component.html
> -              min="0"
@filma80 theese values shouldn't be static. Maybe we shoudl review data model of the service

2021-05-24 09:53 UTC, GiovanniMancini requested changes
Configuration variables shouldn't be static

2021-06-03 08:54 UTC, filma80 commented on src/app/pages/tributi-page/tributi-step1-imposta-enti/tributi-step1-imposta-enti.component.html
> -              min="0"
I suggest to open a new PR for eventual extra modifications as constant values to extract like this one

2021-06-14 16:25 UTC, GiovanniMancini approved these changes

2021-06-14 16:26 UTC, merged