[PTT-187] configure service empty installments dates
pagopa/hub-pa-fe pull request #22
Opened 2021-05-24 08:58 UTC by filma80

#### List of Changes
Empty dates are no longer valid in configure service page.

#### Motivation and Context
Empty dates are not allowed for configure service.

#### How Has This Been Tested?
Unit and integration tests.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-05-24 09:54 UTC, GiovanniMancini commented on src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
> +      if (!elem.dueDate || (!this.isDateAfter_30_06_2021(elem.dueDate) && elem.percentageSecondary > 0)) {
This data may change. It shouldn't be static

2021-05-24 09:55 UTC, GiovanniMancini requested changes
30-06-2021 shoudln't be harcoded

2021-05-25 08:38 UTC, filma80 commented
It will be added a new boolean to environment constants to enable 30/06 checks.

2021-05-25 09:01 UTC, filma80 commented
Added boolean to enable or disable checks.

2021-05-25 11:12 UTC, GiovanniMancini approved these changes

2021-05-25 11:12 UTC, GiovanniMancini commented
@filma80 please resolve conflicts with the main branch

2021-05-25 14:55 UTC, merged