[PTT-186] configure service secondary percentages
pagopa/hub-pa-fe pull request #23
Opened 2021-05-24 09:58 UTC by filma80

#### List of Changes
Secondary percentages (TEFA) are disabled based on installment date.

#### Motivation and Context
REF-P can't insert TEFA for dates before 1/7/2021

#### How Has This Been Tested?
Unit and integration tests.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-05-25 07:51 UTC, GiovanniMancini commented on src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
> +    if (!this.isDateAfter_30_06_2021(dueDate?.value)) {
This date shouldn't be hardcoded

2021-05-25 07:51 UTC, GiovanniMancini requested changes
Please remove hardcoded values

2021-05-25 08:23 UTC, filma80 commented on src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
> +    if (!this.isDateAfter_30_06_2021(dueDate?.value)) {
This date is already parameterized in PTT-187

2021-05-25 08:23 UTC, filma80 commented
This date is already parameterized in PTT-187

2021-05-31 16:03 UTC, GiovanniMancini approved these changes

2021-05-31 16:03 UTC, merged