[PTT-189] configure service installment dates order
pagopa/hub-pa-fe pull request #29
Opened 2021-05-24 15:24 UTC by filma80

#### List of Changes
Installment dates are now checked for date order.

#### Motivation and Context
Installments needs to be ordered by date.

#### How Has This Been Tested?
Unit and integration tests.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-05-25 07:42 UTC, GiovanniMancini commented on src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
> +        (!this.isDateAfter_30_06_2021(elem.dueDate) && elem.percentageSecondary > 0) ||
This date can't be hard coded

2021-05-25 07:43 UTC, GiovanniMancini requested changes
Please remove hard coded variables

2021-05-25 08:08 UTC, filma80 commented on src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
> +        (!this.isDateAfter_30_06_2021(elem.dueDate) && elem.percentageSecondary > 0) ||
this date is already parameterized in PTT-187

2021-05-26 08:45 UTC, GiovanniMancini approved these changes

2021-05-26 08:45 UTC, merged